# Generated by Django 4.1.3 on 2022-11-14 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinetid', models.IntegerField(db_index=True, help_text='Номер кабинета')),
                ('name', models.CharField(db_index=True, help_text='Название кабинета', max_length=48)),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueid', models.IntegerField(blank=True, db_index=True, help_text='Номер очереди')),
                ('priority', models.IntegerField(db_index=True, default='0', help_text='Приоритет в очереди')),
                ('cabinetid', models.ForeignKey(help_text='Кабинет', on_delete=django.db.models.deletion.PROTECT, to='equeueapp.cabinet')),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очереди',
            },
        ),
    ]
